# Generated by Django 5.0.6 on 2024-09-30 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdentityDocumentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OTHR", "Other"),
                            ("PSPT", "Passport"),
                            ("DRLC", "Driver's License"),
                            ("CACS", "Canadian Citizenship"),
                            ("CAPP", "Canadian Passport"),
                            ("CIC", "Citizenship and Immigration Canada Form"),
                            ("CIS", "Certificate of Indian Status"),
                            ("CON", "Certificate of Naturalization"),
                            ("OT", "Other document bearing photo and signature"),
                            ("PHI", "Provincial Health Insurance Card"),
                            ("PRC", "Permanent Resident Card"),
                            ("SIN", "Social Insurance Card"),
                            ("CFL", "Canadian Firearms Licence"),
                            ("BRTH", "Birth Certificate"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "identifier_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expiry", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "identity_document_info",
            },
        ),
    ]
